### ISSUE TITLE
PaaS for AWS users whitepaper

### ISSUE THREAD

**Issue by skibum55** [pivotalservices/thebeach#16]
PaaS for AWS users whitepaper.  Like this one for  vsphere: https://docs.google.com/a/pivotal.io/document/d/1Ed_Dj0irLPUXPVTrkyK8SNOUufMf6YPXjf7ULDUotio/edit?usp=sharing

**Comment by jszod** [comment]
This is a duplicate of story: https://www.pivotaltracker.com/story/show/111696272
