### ISSUE TITLE
New hire training

### ISSUE THREAD

**Issue by skibum55** [pivotalservices/thebeach#17]
We should put together some new hire training to ensure team members can contribute quickly.

**Comment by skibum55** [comment]
Duplicate of https://www.pivotaltracker.com/story/show/111728118

**Comment by joefitzgerald** [comment]
Not sure this is a duplicate of that story @skibum55. New hire training / an onboarding guide is definitely valuable and not constrained to just guiding them to beach projects.

**Comment by jszod** [comment]
This is a duplicate story of: https://www.pivotaltracker.com/story/show/111267528
